// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dculagxzejeibgzmqasy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdWxhZ3h6ZWplaWJnem1xYXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODkzMDksImV4cCI6MjA3NDI2NTMwOX0.oUF2Rn6sYrN00IyGv0gCbP6lvpIuSQYCyQ5pmmKHYIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});